# 必填
机器人密钥: ""
# 主人id,必填,支持多个
主人:
  -

# 代理地址,留空为不使用代理
代理地址:

# 日志等级,可选: DEBUG INFO WARN ERROR 还有什么我忘了,建议保持默认
控制台日志等级: "INFO"
文件日志等级: "DEBUG"

# 支持多下载器(wip)
# 下载器名: 自定义,将作为标识
# 下载器地址: 示例: http://127.0.0.1:6800/jsonrpc
# 下载器密钥: 即你设置的rpc密钥
下载器组:
  - 下载器名: ""
    下载器地址: ""
    下载器密钥: ""
  - 下载器名: ""
    下载器地址: ""
    下载器密钥: ""
